name: receitas
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Adicione a dependência do pacote "receitas"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/almodega.jpg
    - assets/molho.jpg
    - assets/paonachapa.jpg
    - assets/cookies.jpg
    - assets/tacosdecarne.jpg
    - assets/pizza.jpg
